fix: fix disk and port manage, add snapshot object
rustack-cloud-platform/rcp-python pull request #6
Opened 2023-02-09 12:49 UTC by Uatapatau

2023-02-10 00:38 UTC, pilat commented on esu/tests/test_vm.py
> +# @load_fixtures
Why did you decide to comment those tests?

2023-02-10 00:46 UTC, pilat commented on esu/base.py
> +                    except TypeError:
That approach in a library makes the behaviour implicit

2023-02-10 00:46 UTC, pilat commented on esu/router.py
> -    def add_port(self, port):
Looks like a major changes. I'd suggest either keep old methods to backward-compatibility either increase the major version of rustack-esu.
Just imagine someone has an application which uses rustack-esu and something like `>= '1.0.0'` in a `requirements.txt` file. With such kind of changes we might broke dependant applications.

2023-02-10 00:49 UTC, pilat requested changes

2023-02-10 00:49 UTC, pilat commented on esu/vm.py
> -    def add_disk(self, disk):
Once again it looks like a major changes. Did I miss something?

2023-02-13 05:47 UTC, Uatapatau commented on esu/tests/test_vm.py
> +# @load_fixtures
Тесты очень геморройные в написании, и от части не сильно проверяют функционал.
Эту библиотеку будут использовать для тестирования, и так или иначе все ошибки связанные с работой библиотеки найдут.

2023-02-13 05:47 UTC, Uatapatau commented on esu/base.py
> +                    except TypeError:
В некоторых случаях это ломает работу библиотеки.
Например если получить роутер созданный в панели, то прилетит файрвол с пустым vdc, и из-за этого появится ошибка.

2023-02-13 05:47 UTC, Uatapatau commented on esu/router.py
> -    def add_port(self, port):
Да ты прав, я поправлю

2023-02-13 05:47 UTC, Uatapatau commented on esu/vm.py
> -    def add_disk(self, disk):
Решили немного поменять логику работы с подключением портов и дисков.

2023-02-13 07:32 UTC, closed without merging